# Generated by Django 2.1.3 on 2018-11-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_number', models.IntegerField(max_length=10)),
                ('dishes_name', models.CharField(max_length=50)),
                ('dishes_img', models.ImageField(upload_to='')),
                ('dishes_price', models.FloatField(max_length=10)),
                ('dishes_cursine', models.IntegerField(max_length=1)),
                ('dishes_taste', models.IntegerField(max_length=1)),
                ('dishes_healthy', models.IntegerField(max_length=10)),
                ('dishes_hot', models.IntegerField(max_length=10)),
            ],
        ),
    ]
